global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "postgres"
    static_configs:
      - targets: [ "postgres-exporter:9187" ]

  - job_name: "habit-config-server"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8889"]

  - job_name: "habit-eureka-server"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:8761" ]

  # Discover targets from Eureka and scrape metrics from them (Whitebox monitoring)
  - job_name: "eureka-discovery"
    eureka_sd_configs:
      - server: "http://host.docker.internal:8761/eureka"
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [ __meta_eureka_app_name ]
        target_label: application
      - source_labels: [ __meta_eureka_app_instance_metadata_metrics_path ]
        target_label: __metrics_path__
      - source_labels: [ __address__ ]
        target_label: instance
      - source_labels: [ __address__ ]
        target_label: __address__
        regex: "localhost:(.*)"
        replacement: "host.docker.internal:$1"

  # Discover targets from Eureka and probe the health endpoints via the Blackbox Exporter (Blackbox monitoring)
  - job_name: "blackbox-via-service-discovery"
    params:
      module:
        - "http_2xx"
    metrics_path: "/probe"
    eureka_sd_configs:
      - server: "http://host.docker.internal:8761/eureka"
        refresh_interval: "30s"
    relabel_configs:
      - source_labels: [ "__meta_eureka_app_name" ]
        target_label: "application"
      - source_labels: [ "__meta_eureka_app_instance_healthcheck_url" ]
        target_label: "__param_target"
      - source_labels: [ "__address__" ]
        target_label: "instance"
      - target_label: "__address__"
        replacement: "blackbox-exporter:9115"