server:
  port: 8080

spring:
  application:
    name: habit-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: habit-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/habits/**
            - id: checkin-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/checkins/**
      default-filters:
        - AddResponseHeader=X-Gateway, HabitGateway
